### ISSUE TITLE
Currently there are 9 forks of this project. Proposal to unify the contributors of this project moving forward.

### ISSUE THREAD

**Issue by mattslight** [code-matt/react-native-replaykit#13]
Since there seems to be only a small community relying on this project, it would be better that we get those developers working on forks to contribute back to the main project.

Also there doesn't seem to be any other project offering ReplayKit support in React Native

@code-matt what do you think?

**Comment by code-matt** [comment]
I am not sure what all they are up to. One fork started in app audio recording which I ended up pulling back in myself since no PR was opened.

I agree, PRs are welcomed. I think 0.59+ support needs to be figured out above anything first.

**Comment by mattslight** [comment]
OK I will contact the other repo owners and see if they are willing to help support this central repo.

It is in their interest after all.
