### ISSUE TITLE
Example App

### ISSUE THREAD

**Issue by samridhgupta** [code-matt/react-native-replaykit#3]
The repo needs an example app for a new user to understand the setup process.

**Comment by code-matt** [comment]
I don't know about an example app, that would be overkill for how this works. I will make an example component this weekend.

**Comment by code-matt** [comment]
I went ahead and made the testapp. Also considering the state of my project that uses this module: good idea. Was making things difficult :)

It has basic record, stop, copy, delete and preview functionality.  I should put something moving on the screen when I get time 😂
