### ISSUE TITLE
SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'RNReactNativeReplaykit')

### ISSUE THREAD

**Issue by progmatical** [code-matt/react-native-replaykit#4]
Hi, after upgrading my xCode I'm unable to use this library because of this error: 
`SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'RNReactNativeReplaykit')`

Downgrading the xCode is also not helping, because I cannot then connect to my up-to-date iOS version.

Another version of this error I'm getting is: 
`The target “RNReactNativeReplaykit” contains source code developed with Swift 3.x. This version of Xcode does not support building or migrating Swift 3.x targets.`

Can you please update this library, or give me a clue how I might help? I'll try, but so far I'm only JS developer so a bit of help with iOS development would be great, thanks.

**Comment by code-matt** [comment]
I will take a look this weekend, thanks for the heads up. Have not used this since upgrading myself.

**Comment by code-matt** [comment]
@samridhgupta took care of this, 1.0.8 is on NPM. Please check to see the new option that needs to be passed into `initialize` as well
