### ISSUE TITLE
Exception '*** -[AVAssetWriter finishWritingWithCompletionHandler:] Cannot call method when status is 0' was thrown while invoking stopRecording on target RNReactNativeReplaykit with params 

### ISSUE THREAD

**Issue by ethicalvats** [code-matt/react-native-replaykit#7]
![Simulator Screen Shot - iPhone X - 2019-06-23 at 23 22 38](https://user-images.githubusercontent.com/1000068/59980054-017a1f80-960e-11e9-88e9-e35ca26db179.png)

{
...
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.4.0",
    "firebase": "^5.11.1",
    "net": "^1.0.2",
    "querystring": "^0.2.0",
    "react": "16.8.3",
    "react-debugger": "0.0.1",
    "react-native": "0.59.5",
    "react-native-animatable": "^1.3.2",
    "react-native-audio-toolkit": "^1.0.6",
    "react-native-camera": "^2.6.0",
    "react-native-datepicker": "^1.7.2",
    "react-native-elements": "^1.1.0",
    "react-native-fbsdk": "^0.8.0",
    "react-native-firebase": "^5.3.1",
    "react-native-fs": "^2.13.3",
    "react-native-gesture-handler": "^1.2.1",
    "react-native-image-picker": "^0.28.1",
    "react-native-image-slider": "^2.0.3",
    "react-native-infinity-slider": "^1.0.3",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-linear-gradient": "^2.5.4",
    "react-native-list-slider": "^1.1.1",
    "react-native-media-queries": "^0.3.0",
    "react-native-modal": "^10.0.0",
    "react-native-reanimated": "^1.0.1",
    "react-native-replaykit": "^1.1.0",
    "react-native-responsive-fontsize": "^0.1.8",
    "react-native-responsive-screen": "^1.2.2",
    "react-native-share": "https://github.com/react-native-community/react-native-share/archive/v1.2.0.tar.gz",
    "react-native-size-matters": "^0.2.1",
    "react-native-switch": "^1.5.0",
    "react-native-tab-view": "^2.2.0",
    "react-native-typography": "^1.4.0",
    "react-native-vector-icons": "^6.4.2",
    "react-native-video": "^4.4.1",
    "react-navigation": "^3.9.1",
    "react-redux": "^7.0.3",
    "recyclerlistview": "^1.3.4",
    "redux": "^4.0.1",
    "redux-persist": "^5.10.0",
    "request": "^2.88.0",
    "request-promise-native": "^1.0.7",
    "rn-vertical-slider": "^1.0.4",
    "youtube-search": "^1.1.4"
  },
  "devDependencies": {
    "@babel/core": "7.4.4",
    "@babel/runtime": "7.4.4",
    "babel-jest": "24.7.1",
    "jest": "24.7.1",
    "metro-react-native-babel-preset": "0.54.0",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "./assets/fonts/"
    ]
  }
}

Need help!

**Comment by ethicalvats** [comment]
The recording doesn't work on iOS simulators, thanks

**Comment by code-matt** [comment]
Wow that is a good catch, I will put that front and center in Readme. This weekend will see if there is a way the simulator can record. Thank you for letting me know what it was 👍
